# Generated by Django 5.1.6 on 2025-02-17 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodels',
            name='comments',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='post',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to='community.postmodels'),
        ),
    ]
