import React, { createContext } from "react";

import domates from "./Images/plants/domates.png"
import salatalik from "./Images/plants/salatalık.png"
import biber from "./Images/plants/biber.png"
import marul from "./Images/plants/marul.png"
import patlican from "./Images/plants/patlıcan.png"
import kabak from "./Images/plants/kabak.png"
import fasulye from "./Images/plants/fasulye.png"
import bezelye from "./Images/plants/bezelye.png"
import havuc from "./Images/plants/havuç.png"
import turp from "./Images/plants/turp.png"
import sogan from "./Images/plants/soğan.png"
import sarimsak from "./Images/plants/sarımsak.png"
import ispanak from "./Images/plants/ıspanak.png"
import brokoli from "./Images/plants/brokoli.png"
import lahana from "./Images/plants/lahana.png"
import pancar from "./Images/plants/pancar.png"
import patates from "./Images/plants/patates.png"
import cilek from "./Images/plants/çilek.png"
import kinoa from "./Images/plants/kinoa.png"
import roka from "./Images/plants/roka.png"
import nane from "./Images/plants/nane.png"
import maydanoz from "./Images/plants/maydonoz.png"
import dereotu from "./Images/plants/dereotu.png" 
import feslegen from "./Images/plants/fesleğen.png"
import kekik from "./Images/plants/kekik.png"
import biberiye from "./Images/plants/biberiye.png"
import adacayi from "./Images/plants/adaçayı.png"
import lavanta from "./Images/plants/lavanta.png"
import zerdecal from "./Images/plants/zerdeçal.png"
import zencefil from "./Images/plants/zencefil.png"
import papatya from "./Images/plants/papatya.png"
import melisa from "./Images/plants/melisa.png"
import bruksellahanasi from "./Images/plants/brüksel.png"
import mercimek from "./Images/plants/mercimek.png"
import nohut from "./Images/plants/nohut.png"
import barbunya from "./Images/plants/barbunya.png"
import bakla from "./Images/plants/bakla.png"
import pirasa from "./Images/plants/pırasa.png"
import rezene from "./Images/plants/rezene.png"
import semizotu from "./Images/plants/semizotu.png"
import frenksogani from "./Images/plants/frenk.png"
import defne from "./Images/plants/defne.png"
import reyhan from "./Images/plants/reyhan.png"
import suteresi from "./Images/plants/suteresi.png"
import bogurtlen from "./Images/plants/böğürtlen.png"
import ahududu from "./Images/plants/ahududu.png"
import mantar from "./Images/plants/mantar.png"
import kirizilahana from "./Images/plants/kırmızı.png"
import enginar from "./Images/plants/enginar.png"

export const CropContext = createContext();
const Crops = [
  { name: "Domates", scientificName: "Solanum lycopersicum", preferredTemperature: { min: 20, max: 28 }, wateringPerDay: 0.45, maintenanceCost: 15, efficiency: 8, altitude: { min: 0, max: 1000 }, src: domates, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.5, growingSeason: "Yaz", harvestTime: "8-10 hafta", shortDescription: "Verimli meyve verir.", longDescription: "Domates, düzenli sulama ve dengeli gübreleme gerektirir. Saksı toprağının iyi drene olduğundan emin olun. Çiçek açtıktan sonra 8-10 hafta içinde olgun meyveler hasat edilir. Düzenli budama ve destek kullanımı verimi artırır." },
  { name: "Salatalık", scientificName: "Cucumis sativus", preferredTemperature: { min: 18, max: 26 }, wateringPerDay: 0.40, maintenanceCost: 12, efficiency: 8, altitude: { min: 0, max: 800 }, src: salatalik, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.8, growingSeason: "Yaz", harvestTime: "6-8 hafta", shortDescription: "Taze ve gevrek meyve verir.", longDescription: "Salatalık, destek gerektiren sürgünlü bir bitkidir. Bol güneş ışığı ve düzenli sulama ile hızlı büyür. 6-8 hafta sonra taze meyveleri hasat edilebilir. Saksı toprağının nemi korunmalıdır." },
  { name: "Biber", scientificName: "Capsicum annuum", preferredTemperature: { min: 20, max: 30 }, wateringPerDay: 0.50, maintenanceCost: 15, efficiency: 7, altitude: { min: 0, max: 1000 }, src: biber, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.5, growingSeason: "Yaz", harvestTime: "8-10 hafta", shortDescription: "Küçük saksılarda yetişir.", longDescription: "Biber, saksıda yetiştirildiğinde düzenli sulama ve besin desteği ile iyi verim verir. Toprağın nemi korunmalı, sulama aralıkları sabit tutulmalıdır. Hasat, çiçek açtıktan yaklaşık 8-10 hafta sonra yapılır." },
  { name: "Marul", scientificName: "Lactuca sativa", preferredTemperature: { min: 15, max: 22 }, wateringPerDay: 0.35, maintenanceCost: 10, efficiency: 9, altitude: { min: 0, max: 600 }, src: marul, lightRequired: "Orta Derecede Işık Almalı", spaceRequired: 0.3, growingSeason: "İlkbahar, Sonbahar", harvestTime: "4-6 hafta", shortDescription: "Hızlı büyür.", longDescription: "Marul, düşük sıcaklıklarda en iyi performansı gösterir. Düzenli ve ölçülü sulama ile 4-6 hafta sonra taze yapraklar hasat edilir. Saksıların serin tutulması önemlidir." },
  { name: "Patlıcan", scientificName: "Solanum melongena", preferredTemperature: { min: 22, max: 30 }, wateringPerDay: 0.55, maintenanceCost: 18, efficiency: 6, altitude: { min: 0, max: 800 }, src: patlican, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.7, growingSeason: "Yaz", harvestTime: "10-12 hafta", shortDescription: "Düşük verimli çeşitler.", longDescription: "Patlıcan, sıcak ortamlarda iyi verim verir. Düzenli sulama ve toprak pH'sına dikkat edilmelidir. Çiçeklenmeden önce hafif budama, meyve verimini artırır. Hasat, çiçek açtıktan yaklaşık 10-12 hafta sonra yapılır." },
  { name: "Kabak", scientificName: "Cucurbita pepo", preferredTemperature: { min: 20, max: 28 }, wateringPerDay: 0.50, maintenanceCost: 12, efficiency: 8, altitude: { min: 0, max: 800 }, src: kabak, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 1.0, growingSeason: "Yaz", harvestTime: "8-10 hafta", shortDescription: "Dwarf çeşitler tercih edilmeli.", longDescription: "Kabak, geniş kök alanı gerektirir; dwarf çeşitler tercih edilmeli. Düzenli sulama ve organik gübre ile saksıda yetiştirilebilir. Hasat, meyve olgunlaştığında, 8-10 hafta sonra yapılır." },
  { name: "Fasulye", scientificName: "Phaseolus vulgaris", preferredTemperature: { min: 20, max: 30 }, wateringPerDay: 0.45, maintenanceCost: 10, efficiency: 7, altitude: { min: 0, max: 1000 }, src: fasulye, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.5, growingSeason: "Yaz", harvestTime: "8-10 hafta", shortDescription: "Asma şeklinde yetişir.", longDescription: "Fasulye, asma formunda saksıda yetiştirilebilir. Yeterli destek verildiğinde, düzenli sulama ile iyi verim sağlar. Çiçeklenmeden 8-10 hafta sonra taze fasulye hasadı yapılır." },
  { name: "Bezelye", scientificName: "Pisum sativum", preferredTemperature: { min: 15, max: 25 }, wateringPerDay: 0.40, maintenanceCost: 8, efficiency: 8, altitude: { min: 0, max: 1000 }, src: bezelye, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.4, growingSeason: "İlkbahar", harvestTime: "6-8 hafta", shortDescription: "Dikey destekle yetişir.", longDescription: "Bezelye, saksıda dikey destek ile kolayca yetişir. Serin ilkbahar koşullarında en iyi verimi verir. 6-8 hafta sonra taze bezelyeler hasat edilebilir." },
  { name: "Havuç", scientificName: "Daucus carota", preferredTemperature: { min: 16, max: 24 }, wateringPerDay: 0.30, maintenanceCost: 8, efficiency: 9, altitude: { min: 0, max: 1200 }, src: havuc, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.3, growingSeason: "Yaz", harvestTime: "10-12 hafta", shortDescription: "Derin, gevşek toprakta yetişir.", longDescription: "Havuç, derin ve gevşek saksı topraklarında daha iyi büyür. Düzenli sulama ve toprağın havalandırılması gerekir. Çiçek açmadan önce, yaklaşık 10-12 hafta sonra kökler hasat edilir." },
  { name: "Turp", scientificName: "Raphanus sativus", preferredTemperature: { min: 15, max: 22 }, wateringPerDay: 0.30, maintenanceCost: 8, efficiency: 8, altitude: { min: 0, max: 800 }, src: turp, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.3, growingSeason: "İlkbahar", harvestTime: "4-6 hafta", shortDescription: "Hızlı hasat.", longDescription: "Turp, hızlı hasat edilen bir sebzedir. Hafif ve iyi drene olan topraklarda, düzenli sulama ile 4-6 hafta içinde olgunlaşır. Saksıdaki turp, kolaylıkla toplanabilir." },
  { name: "Soğan", scientificName: "Allium cepa", preferredTemperature: { min: 12, max: 24 }, wateringPerDay: 0.30, maintenanceCost: 8, efficiency: 8, altitude: { min: 0, max: 1200 }, src: sogan, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.3, growingSeason: "Sonbahar", harvestTime: "10-12 hafta", shortDescription: "Kolay yetişir.", longDescription: "Soğan, soğuk mevsimlerde saksıda yetiştirilebilir. Düzenli sulama ve besin desteği ile 10-12 haftada olgunlaşır. Saksıda yetiştirilen soğanlar, toprak değiştirilerek verim artırılabilir." },
  { name: "Sarımsak", scientificName: "Allium sativum", preferredTemperature: { min: 10, max: 24 }, wateringPerDay: 0.30, maintenanceCost: 8, efficiency: 8, altitude: { min: 0, max: 1200 }, src: sarimsak, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.3, growingSeason: "Sonbahar", harvestTime: "8-10 hafta", shortDescription: "Saksıda yetiştirilebilir.", longDescription: "Sarımsak, saksıda kolayca yetişir. Toprak iyi drene edilmeli ve hafif nemli tutulmalıdır. Çiçeklenmeden 8-10 hafta sonra soğan altı hasat edilir." },
  { name: "Ispanak", scientificName: "Spinacia oleracea", preferredTemperature: { min: 10, max: 20 }, wateringPerDay: 0.35, maintenanceCost: 8, efficiency: 8, altitude: { min: 0, max: 800 }, src: ispanak, lightRequired: "Orta Derecede Işık Almalı", spaceRequired: 0.4, growingSeason: "İlkbahar", harvestTime: "4-6 hafta", shortDescription: "Hızlı büyür.", longDescription: "Ispanak, serin havalarda saksıda hızlı büyür. Düzenli sulama ve hafif gübreleme ile 4-6 hafta sonra taze yapraklar toplanır." },
  { name: "Brokoli", scientificName: "Brassica oleracea italica", preferredTemperature: { min: 16, max: 24 }, wateringPerDay: 0.45, maintenanceCost: 15, efficiency: 7, altitude: { min: 0, max: 1200 }, src: brokoli, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.7, growingSeason: "Sonbahar", harvestTime: "10-12 hafta", shortDescription: "Mini brokoli.", longDescription: "Brokoli, iyi drene toprak ve düzenli sulama gerektirir. Mini brokoli türleri, 10-12 hafta sonra olgunlaşır; saksıda budama ile verim artırılabilir." },
  { name: "Lahana", scientificName: "Brassica oleracea capitata", preferredTemperature: { min: 15, max: 25 }, wateringPerDay: 0.45, maintenanceCost: 12, efficiency: 7, altitude: { min: 0, max: 1200 }, src: lahana, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.8, growingSeason: "Sonbahar", harvestTime: "10-12 hafta", shortDescription: "Mini lahana.", longDescription: "Lahana, saksıda yetiştirildiğinde düzenli sulama ve toprak gübrelemesi ile 10-12 hafta içinde hasat edilebilir. Yaprakların kalitesi budama ile desteklenir." },
  { name: "Pancar", scientificName: "Beta vulgaris", preferredTemperature: { min: 16, max: 26 }, wateringPerDay: 0.40, maintenanceCost: 10, efficiency: 8, altitude: { min: 0, max: 1200 }, src: pancar, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.4, growingSeason: "Yaz", harvestTime: "10-12 hafta", shortDescription: "Küçük saksıda yetişir.", longDescription: "Pancar, saksıda derin, gevşek toprakta iyi gelişir. Düzenli sulama ile 10-12 hafta sonra olgun pancarlar elde edilir." },
  { name: "Patates", scientificName: "Solanum tuberosum", preferredTemperature: { min: 15, max: 25 }, wateringPerDay: 0.60, maintenanceCost: 15, efficiency: 7, altitude: { min: 200, max: 1500 }, src: patates, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 1.0, growingSeason: "Yaz", harvestTime: "12-16 hafta", shortDescription: "Saksı torbası yöntemi.", longDescription: "Patates, derin saksı torbalarında yetiştirilir. Toprağın nem dengesine dikkat edilmeli ve 12-16 hafta sonra toplanmalıdır." },
  { name: "Çilek", scientificName: "Fragaria × ananassa", preferredTemperature: { min: 15, max: 25 }, wateringPerDay: 0.40, maintenanceCost: 15, efficiency: 8, altitude: { min: 0, max: 800 }, src: cilek, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.3, growingSeason: "İlkbahar", harvestTime: "4-6 hafta", shortDescription: "Asılı saksı sistemi.", longDescription: "Çilek, saksıda asılı sistemlerde veya saksı tepsilerinde kolayca yetişir. Düzenli sulama ve gübreleme ile 4-6 hafta içinde taze meyve verir." },
  { name: "Kinoa", scientificName: "Chenopodium quinoa", preferredTemperature: { min: 15, max: 25 }, wateringPerDay: 0.50, maintenanceCost: 20, efficiency: 8, altitude: { min: 0, max: 1000 }, src: kinoa, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.4, growingSeason: "Yaz", harvestTime: "10-12 hafta", shortDescription: "Küçük saksıda yetiştirilebilir.", longDescription: "Kinoa, saksıda küçük alanlarda yetiştirilebilir. İyi drene edilmiş toprak ve düzenli sulama ile 10-12 hafta sonunda olgunlaşır." }, 
  { name: "Roka", scientificName: "Eruca sativa", preferredTemperature: { min: 10, max: 20 }, wateringPerDay: 0.30, maintenanceCost: 10, efficiency: 8, altitude: { min: 0, max: 800 }, src: roka, lightRequired: "Orta Derecede Işık Almalı", spaceRequired: 0.3, growingSeason: "İlkbahar", harvestTime: "4-6 hafta", shortDescription: "Hızlı hasat.", longDescription: "Roka, hızlı büyüyen bir yapraklı sebzedir. Az yer kaplar ve 4-6 hafta içinde taze yaprakları hasat edilebilir. Hafif sulama ve periyodik budama gerekir." },
  { name: "Nane", scientificName: "Mentha spicata", preferredTemperature: { min: 10, max: 25 }, wateringPerDay: 0.40, maintenanceCost: 12, efficiency: 8, altitude: { min: 0, max: 800 }, src: nane, lightRequired: "Orta Derecede Işık Almalı", spaceRequired: 0.3, growingSeason: "İlkbahar", harvestTime: "6-8 hafta", shortDescription: "Yoğun yayılır.", longDescription: "Nane, saksıda yoğun yayılır ve hafif gölgelik alanlarda iyi gelişir. Yapraklar 6-8 hafta sonunda toplanabilir; taze veya kurutulmuş olarak kullanılabilir." },
  { name: "Maydanoz", scientificName: "Petroselinum crispum", preferredTemperature: { min: 10, max: 25 }, wateringPerDay: 0.40, maintenanceCost: 12, efficiency: 8, altitude: { min: 0, max: 800 }, src: maydanoz, lightRequired: "Orta Derecede Işık Almalı", spaceRequired: 0.3, growingSeason: "İlkbahar", harvestTime: "4-6 hafta", shortDescription: "Kolay yetişir.", longDescription: "Maydanoz, saksıda kolayca yetişir. Düzenli sulama ve toprak gübrelemesi ile 4-6 hafta sonra taze yaprakları hasat edilir." },
  { name: "Dereotu", scientificName: "Anethum graveolens", preferredTemperature: { min: 10, max: 25 }, wateringPerDay: 0.40, maintenanceCost: 12, efficiency: 8, altitude: { min: 0, max: 800 }, src: dereotu, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.3, growingSeason: "İlkbahar", harvestTime: "4-6 hafta", shortDescription: "Hafif aromalı.", longDescription: "Dereotu, hafif aroması ile bilinir. Saksıda kolayca yetişir ve yaprakları 4-6 hafta sonra taze olarak hasat edilebilir." },
  { name: "Fesleğen", scientificName: "Ocimum basilicum", preferredTemperature: { min: 20, max: 30 }, wateringPerDay: 0.50, maintenanceCost: 15, efficiency: 8, altitude: { min: 0, max: 800 }, src: feslegen, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.4, growingSeason: "Yaz", harvestTime: "8-10 hafta", shortDescription: "Aromatik ve verimli.", longDescription: "Fesleğen, mutfak kullanımına uygun, aromatik bir bitkidir. Düzenli sulama ve gübre ile 8-10 hafta sonunda yaprakları hasat edilir. Hafif budama verimi artırır." },
  { name: "Kekik", scientificName: "Thymus vulgaris", preferredTemperature: { min: 15, max: 25 }, wateringPerDay: 0.40, maintenanceCost: 12, efficiency: 8, altitude: { min: 0, max: 800 }, src: kekik, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.3, growingSeason: "Yaz", harvestTime: "6-8 hafta", shortDescription: "Aromatik, hızlı hasat.", longDescription: "Kekik, aromatik yapısı ile bilinir. İyi drene toprakta, düzenli sulama ile 6-8 hafta sonra yaprakları toplanır. Saksıda kolayca yetişir." },
  { name: "Biberiye", scientificName: "Rosmarinus officinalis", preferredTemperature: { min: 15, max: 25 }, wateringPerDay: 0.40, maintenanceCost: 15, efficiency: 8, altitude: { min: 0, max: 800 }, src: biberiye, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.5, growingSeason: "Yaz", harvestTime: "8-10 hafta", shortDescription: "Düşük boylu ve aromatik.", longDescription: "Biberiye, saksıda verimli yetişen, düşük boylu ve aromatik bir bitkidir. Düzenli sulama ve budama ile 8-10 hafta sonra yaprakları hasat edilir." },
  { name: "Adaçayı", scientificName: "Salvia officinalis", preferredTemperature: { min: 15, max: 25 }, wateringPerDay: 0.40, maintenanceCost: 15, efficiency: 8, altitude: { min: 0, max: 800 }, src: adacayi, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.4, growingSeason: "Yaz", harvestTime: "8-10 hafta", shortDescription: "Sağlık açısından faydalı.", longDescription: "Adaçayı, saksıda kolayca yetiştirilebilir ve sağlık açısından faydalıdır. Düzenli sulama ve hafif gübre ile 8-10 hafta sonunda yaprakları hasat edilir." },
  { name: "Lavanta", scientificName: "Lavandula angustifolia", preferredTemperature: { min: 15, max: 30 }, wateringPerDay: 0.30, maintenanceCost: 18, efficiency: 8, altitude: { min: 0, max: 800 }, src: lavanta, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.5, growingSeason: "Yaz", harvestTime: "10-12 hafta", shortDescription: "Dekoratif ve kokulu.", longDescription: "Lavanta, dekoratif ve hoş kokulu bir bitkidir. İyi drene edilmiş saksılarda, düzenli sulama ve budama ile 10-12 hafta sonra çiçekleri veya yaprakları hasat edilir." },
  { name: "Zerdeçal", scientificName: "Curcuma longa", preferredTemperature: { min: 25, max: 35 }, wateringPerDay: 0.70, maintenanceCost: 25, efficiency: 6, altitude: { min: 0, max: 800 }, src: zerdecal, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.6, growingSeason: "Yaz", harvestTime: "12-16 hafta", shortDescription: "Baharatlık rizom.", longDescription: "Zerdeçal, sıcak iklimlerde saksıda yetiştirilebilir. Düzenli sulama ve toprak nemi korunduğunda 12-16 hafta sonra rizomları hasat edilir. Kurutma işlemine tabi tutulur ve baharat olarak kullanılır." },
  { name: "Zencefil", scientificName: "Zingiber officinale", preferredTemperature: { min: 25, max: 35 }, wateringPerDay: 0.70, maintenanceCost: 25, efficiency: 6, altitude: { min: 0, max: 800 }, src: zencefil, lightRequired: "Orta Derecede Işık Almalı", spaceRequired: 0.6, growingSeason: "Yaz", harvestTime: "12-16 hafta", shortDescription: "Rizom hasadı.", longDescription: "Zencefil, nemli ve sıcak ortamlarda saksıda yetiştirilebilir. Düzenli sulama ile 12-16 hafta sonra rizomları kazılarak toplanır, temizlenir ve kurutulur." },
  { name: "Papatya", scientificName: "Matricaria chamomilla", preferredTemperature: { min: 15, max: 25 }, wateringPerDay: 0.30, maintenanceCost: 10, efficiency: 9, altitude: { min: 0, max: 800 }, src: papatya, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.3, growingSeason: "Yaz", harvestTime: "4-6 hafta", shortDescription: "Rahatlatıcı çiçek.", longDescription: "Papatya, saksıda dekoratif olarak yetiştirilir. Hafif sulama ve gübreleme ile 4-6 hafta sonra çiçek açar; yaprak ve çiçekleri toplanarak doğal rahatlama sağlar." },
  { name: "Melisa", scientificName: "Melissa officinalis", preferredTemperature: { min: 15, max: 25 }, wateringPerDay: 0.30, maintenanceCost: 10, efficiency: 9, altitude: { min: 0, max: 800 }, src: melisa, lightRequired: "Orta Derecede Işık Almalı", spaceRequired: 0.3, growingSeason: "Yaz", harvestTime: "4-6 hafta", shortDescription: "Rahatlatıcı aroma.", longDescription: "Melisa, saksıda küçük alanlarda yetişir. Rahatlatıcı aroması ve lezzetli yaprakları için düzenli sulama ve hafif gübreleme gerekir; 4-6 hafta sonunda yaprakları toplanır." },
  { name: "Brüksel Lahanası", scientificName: "Brassica oleracea gemmifera", preferredTemperature: { min: 15, max: 25 }, wateringPerDay: 0.50, maintenanceCost: 20, efficiency: 7, altitude: { min: 200, max: 1200 }, src: bruksellahanasi, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.7, growingSeason: "Sonbahar", harvestTime: "12-16 hafta", shortDescription: "Mini lahanalar.", longDescription: "Brüksel lahanası, mini türleri saksıda yetiştirilebilir. Düzenli sulama ve soğuk havalarda koruma ile 12-16 hafta sonra olgunlaşır, yapraklar toplanarak tüketilir." },
  { name: "Mercimek", scientificName: "Lens culinaris", preferredTemperature: { min: 18, max: 26 }, wateringPerDay: 0.40, maintenanceCost: 14, efficiency: 8, altitude: { min: 0, max: 1000 }, src: mercimek, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.4, growingSeason: "İlkbahar", harvestTime: "10-12 hafta", shortDescription: "Bakliyat tohumları.", longDescription: "Mercimek, saksıda derin topraklarda yetişir. Düzenli sulama ile 10-12 hafta sonra bakliyat olarak kullanılabilecek olgun mercimek tohumları elde edilir." },
  { name: "Nohut", scientificName: "Cicer arietinum", preferredTemperature: { min: 20, max: 28 }, wateringPerDay: 0.45, maintenanceCost: 15, efficiency: 7, altitude: { min: 0, max: 1000 }, src: nohut, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.4, growingSeason: "Yaz", harvestTime: "10-12 hafta", shortDescription: "Deneysel bakliyat.", longDescription: "Nohut, saksıda yetiştirilebilen bakliyat türüdür. İyi drene edilmiş toprak ve düzenli sulama ile 10-12 hafta sonra hasat edilir." },
  { name: "Barbunya", scientificName: "Phaseolus coccineus", preferredTemperature: { min: 20, max: 30 }, wateringPerDay: 0.45, maintenanceCost: 16, efficiency: 7, altitude: { min: 0, max: 1000 }, src: barbunya, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.5, growingSeason: "Yaz", harvestTime: "10-12 hafta", shortDescription: "Dikey destekle yetişir.", longDescription: "Barbunya, saksıda dikey destekle kolayca yetiştirilebilir. Düzenli sulama ve budama ile 10-12 hafta sonunda taze fasulye benzeri baklagiller elde edilir." },
  { name: "Bakla", scientificName: "Vicia faba", preferredTemperature: { min: 15, max: 25 }, wateringPerDay: 0.50, maintenanceCost: 16, efficiency: 7, altitude: { min: 0, max: 1000 }, src: bakla, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.5, growingSeason: "İlkbahar", harvestTime: "10-12 hafta", shortDescription: "Geniş yapraklı bakliyat.", longDescription: "Bakla, saksıda yetiştirilebilen geniş yapraklı bir bakliyattır. Düzenli sulama ile 10-12 hafta sonunda tohumları elde edilir." },
  { name: "Pırasa", scientificName: "Allium porrum", preferredTemperature: { min: 10, max: 20 }, wateringPerDay: 0.45, maintenanceCost: 18, efficiency: 7, altitude: { min: 0, max: 1000 }, src: pirasa, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.5, growingSeason: "Kış", harvestTime: "12-16 hafta", shortDescription: "Uzun, dar saksı.", longDescription: "Pırasa, uzun ve dar saksılarda yetiştirilebilir. Soğuk havalarda da iyi gelişir; 12-16 hafta sonra, beyaz kısmı özenle kesilerek hasat edilir." },
  { name: "Rezene", scientificName: "Foeniculum vulgare", preferredTemperature: { min: 15, max: 25 }, wateringPerDay: 0.50, maintenanceCost: 17, efficiency: 7, altitude: { min: 0, max: 800 }, src: rezene, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.4, growingSeason: "Yaz", harvestTime: "8-10 hafta", shortDescription: "Aromatik bitki.", longDescription: "Rezene, saksıda yetiştirilebilen aromatik bir bitkidir. Düzenli sulama ve hafif gübreleme ile 8-10 hafta sonra toplanarak yemeklerde kullanılabilir." },
  { name: "Mantar", scientificName: "Agaricus bisporus", preferredTemperature: { min: 15, max: 22 }, wateringPerDay: 0.30, maintenanceCost: 10, efficiency: 9, altitude: { min: 0, max: 800 }, src: mantar, lightRequired: "Orta Derecede Işık Almalı", spaceRequired: 0.3, growingSeason: "Kış", harvestTime: "8-10 hafta", shortDescription: "Özel kitlerle yetişir.", longDescription: "Mantar, özel kitlerle saksıda yetiştirilebilir. Nemli ortam ve düşük ışık koşulları mantarın verimli gelişimini sağlar; 8-10 hafta sonunda hasat edilir." },
  { name: "Kıvırcık Lahana", scientificName: "Brassica oleracea capitata f. rubra", preferredTemperature: { min: 15, max: 25 }, wateringPerDay: 0.70, maintenanceCost: 13, efficiency: 7, altitude: { min: 0, max: 1000 }, src: kirizilahana, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.7, growingSeason: "Sonbahar", harvestTime: "12-16 hafta", shortDescription: "Mini kırmızı lahana.", longDescription: "Kıvırcık lahana mini türleri saksıda yetiştirilebilir. Düzenli sulama, hafif budama ve iyi drene edilmiş toprakla 12-16 hafta sonra renkli yapraklar elde edilir." },
  { name: "Semizotu", scientificName: "Portulaca oleracea", preferredTemperature: { min: 15, max: 25 }, wateringPerDay: 0.40, maintenanceCost: 12, efficiency: 8, altitude: { min: 0, max: 800 }, src: semizotu, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.3, growingSeason: "Yaz", harvestTime: "4-6 hafta", shortDescription: "Hızlı büyür.", longDescription: "Semizotu, saksıda yetiştirildiğinde hızlı büyür ve az yer kaplar. Düzenli sulama ve iyi drene edilmiş toprakla 4-6 hafta içinde taze yapraklar toplanır." },
  { name: "Frenk Soğanı", scientificName: "Allium schoenoprasum", preferredTemperature: { min: 10, max: 25 }, wateringPerDay: 0.35, maintenanceCost: 14, efficiency: 8, altitude: { min: 0, max: 800 }, src: frenksogani, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.3, growingSeason: "Yaz", harvestTime: "4-6 hafta", shortDescription: "Kolay yetişir.", longDescription: "Frenk soğanı, saksıda kolay yetişen küçük soğan çeşididir. Düzenli sulama ve hafif gübreleme ile 4-6 hafta sonunda taze soğan yaprakları elde edilir." },
  { name: "Defne", scientificName: "Laurus nobilis", preferredTemperature: { min: 15, max: 25 }, wateringPerDay: 0.40, maintenanceCost: 16, efficiency: 7, altitude: { min: 0, max: 800 }, src: defne, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.4, growingSeason: "Yaz", harvestTime: "8-10 hafta", shortDescription: "Küçük fidan.", longDescription: "Defne, saksıda küçük boylu fidanlar olarak yetiştirilebilir. Düzenli sulama, uygun toprak ve kısmi budama ile 8-10 hafta sonra defne yaprakları hasat edilir." },
  { name: "Reyhan", scientificName: "Ocimum gratissimum", preferredTemperature: { min: 20, max: 30 }, wateringPerDay: 0.50, maintenanceCost: 15, efficiency: 8, altitude: { min: 0, max: 800 }, src: reyhan, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.4, growingSeason: "Yaz", harvestTime: "8-10 hafta", shortDescription: "Aromatik yapraklı.", longDescription: "Reyhan, saksıda yetiştirilebilen aromatik bir bitkidir. Bol güneş ışığı ve düzenli sulama ile yaprakları 8-10 hafta sonra hasat edilir." },
  { name: "Su Teresi", scientificName: "Nasturtium officinale", preferredTemperature: { min: 10, max: 20 }, wateringPerDay: 0.35, maintenanceCost: 12, efficiency: 8, altitude: { min: 0, max: 800 }, src: suteresi, lightRequired: "Orta Derecede Işık Almalı", spaceRequired: 0.3, growingSeason: "Yaz", harvestTime: "4-6 hafta", shortDescription: "Besleyici.", longDescription: "Su teresi, saksıda kolayca yetiştirilebilen besleyici bir yeşilliktir. Hafif sulama ve uygun ışık koşulları ile 4-6 hafta içinde taze yaprakları toplanır." },
  { name: "Böğürtlen", scientificName: "Rubus fruticosus", preferredTemperature: { min: 15, max: 25 }, wateringPerDay: 0.40, maintenanceCost: 16, efficiency: 8, altitude: { min: 0, max: 800 }, src: bogurtlen, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.5, growingSeason: "Yaz", harvestTime: "10-12 hafta", shortDescription: "Kompakt çeşit.", longDescription: "Böğürtlen, saksıda yetiştirilebilen kompakt bir türdür. Düzenli sulama ve hafif gübreleme ile 10-12 hafta sonra meyveleri toplanır." },
  { name: "Ahududu", scientificName: "Rubus idaeus", preferredTemperature: { min: 15, max: 25 }, wateringPerDay: 0.40, maintenanceCost: 16, efficiency: 8, altitude: { min: 0, max: 800 }, src: ahududu, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.5, growingSeason: "Yaz", harvestTime: "10-12 hafta", shortDescription: "Verimli.", longDescription: "Ahududu, saksıda yetiştirilebilen verimli bir bitkidir. Düzenli sulama ile 10-12 hafta sonra taze meyveler hasat edilir." },
  { name: "Enginar", scientificName: "Cynara scolymus", preferredTemperature: { min: 15, max: 25 }, wateringPerDay: 0.55, maintenanceCost: 20, efficiency: 7, altitude: { min: 0, max: 800 }, src: enginar, lightRequired: "Yüksek Derecede Işık Almalı", spaceRequired: 0.8, growingSeason: "Yaz", harvestTime: "8-10 hafta", shortDescription: "Mini enginar.", longDescription: "Enginar, saksıda mini enginar türleri olarak yetiştirilebilir. Düzenli sulama ve budama ile 8-10 hafta sonra enginar yaprakları toplanır." }
];  


function CropContextProvider({children}) {
  return (
    <>
      <CropContext.Provider value={Crops}>{children}</CropContext.Provider>
    </>
  );
}

export default CropContextProvider;
